
create table if not exists public.cartera_valors (
    id bigint generated by default as identity primary key,
    created_at timestamptz not null default now(),
    updated_at timestamptz,
    nom text not null,
    ticker text not null unique,
    accions numeric not null default 0,
    preu_mitja numeric not null default 0,
    radar text not null default '🟡 Vigilar',
    notes text
);

alter table public.cartera_valors enable row level security;

-- Per una app privada simple amb la clau anon, pots crear una policy adequada
-- des de Supabase. No activis accés públic si l'app ha de ser privada.
